
image:
  repository: ghcr.io/ministryofjustice/hmpps-component-dependencies
  tag: latest

appinsightEnvs: ["DEV", "PREPROD", "PROD"]

cronjobs:
  updateDependencyInfo: 0 */6 * * *

generic-prometheus-alerts:
  targetApplication: hmpps-component-dependencies
  ingressAlertsEnabled: false