
image:
  repository: ghcr.io/ministryofjustice/hmpps-component-dependencies
  tag: latest

imagePython:
  repository: ghcr.io/ministryofjustice/hmpps-component-dependencies-python
  tag: latest

appinsightEnvs: ["DEV", "PREPROD", "PROD"]

cronjobs:
  updateDependencyInfo: 0 */6 * * *
  componentDependencyDiscovery: "45 09,15 * * 2-5"

generic-prometheus-alerts:
  targetApplication: hmpps-component-dependencies
  ingressAlertsEnabled: false