---
# Per environment values which override defaults in hmpps-component-dependencies/values.yaml

redis:
  secretName: elasticache-redis

apis:
  serviceCatalogue:
    url: https://service-catalogue.hmpps.service.justice.gov.uk

generic-prometheus-alerts:
  alertSeverity: hmpps-sre-alerts-prod

discoveryCronJob:
  enabled: true
  cron:
    component_dependency_discovery: "45 0-4/2,10-22/2 * * 2-5"
