---
# Per environment values which override defaults in hmpps-component-dependencies/values.yaml

redis:
  secretName: elasticache-redis

apis:
  serviceCatalogue:
    url: https://service-catalogue-dev.hmpps.service.justice.gov.uk

generic-prometheus-alerts:
  alertSeverity: hmpps-sre-alerts-nonprod

discoveryCronJob:
  enabled: true
  cron:
    component_dependency_discovery: "00 00 * * 2-5"